[cijoe.workflow]
# Change this to true to stop processing additional workflow steps when a step fails
fail_fast=true

[xal]
dev_path="/dev/nvme0n1"
mountpoint="/tmp/xal_testing"

[xal.artifacts]
path="/tmp/artifacts"
