name: build_and_install

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build_and_install:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/refenv/cijoe-docker:v0.9.50

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.2.2

    - name: Prep, Packages
      run: ./toolbox/pkgs/debian.sh

    - name: Configure
      run: make configure

    - name: Build
      run: make build

    - name: Install
      run: make install